---
- lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

- copy:
    src: ./ssh/authorized_keys
    dest: /root/.ssh/authorized_keys
  notify:
    - restart_sshd

- timezone:
    name: Europe/Berlin

- apt:
    name: ufw
    state: present
- apt:
    name: cron
    state: present

- ufw:
    rule: allow
    port: '22'

- ufw:
    state: enabled

- name: Disable password login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify:
    - restart_sshd
