---
- set_fact:
    start_time: "{{ now(True, '%Y-%m-%d %H:%M:%S') }}"
- user:
    name: "{{ user_name }}"
    state: absent
    remove: true

- file:
    path: "/home/{{ user_name }}/"
    state: absent

- docker_container:
    name: "{{ container_name }}"
    state: absent

- docker_image:
    name: "{{ image_name }}"
    state: absent
  when: image_name is defined

- lineinfile:
   path: /etc/crontab
   line: "0 4   * * *   root  docker restart {{ container_name }}"
   state: absent

- ufw:
    delete: true
    rule: allow
    port: '{{ item }}'
  loop:
    "{{ ports }}"

- set_fact:
    end_time: "{{ now(True, '%Y-%m-%d %H:%M:%S') }}"

- set_fact:
    role_return: {time_diff: "{{ ((end_time |to_datetime) - (start_time |to_datetime)).total_seconds()|int }}"}